Repository microsoft/CromwellOnAzure, pull requests merged in 2021-05, with the labels that each got.

#235 Improve logging for private ACRs and update documentation
  docs/troubleshooting-guide.md
  src/TesApi.Web/AzureProxy.cs
Labels: bug, documentation

#232 Create VNET, NSG and Identity in the same region as VM.
  src/deploy-cromwell-on-azure/Deployer.cs
Labels: bug

#240 Exposed components of the Cromwell task description
  src/Tes/Models/TesTaskExtended.cs
Labels: enhancement

#239 Skipping VM sizes that previously failed with "NodeAllocationFailed" when retrying the task
  src/TesApi.Tests/BatchSchedulerTests.cs
  src/TesApi.Web/BatchScheduler.cs
Labels: bug

#244 Allowing users to specify the VM sizes that can be used for Batch scheduling
  src/Tes/Models/VirtualMachineInfo.cs
  src/TesApi.Tests/BatchSchedulerTests.cs
  src/TesApi.Tests/ConfigurationUtilsTests.cs
  src/TesApi.Web/AzureBatchAccountQuotas.cs
  src/TesApi.Web/AzureBillingUtils.cs
  src/TesApi.Web/AzureProxy.cs
  src/TesApi.Web/BatchScheduler.cs
  src/TesApi.Web/ConfigurationUtils.cs
  src/TesApi.Web/DefaultVmPrices.json
  src/TesApi.Web/Startup.cs
  src/deploy-cromwell-on-azure/Deployer.cs
  src/deploy-cromwell-on-azure/deploy-cromwell-on-azure.csproj
  src/deploy-cromwell-on-azure/scripts/allowed-vm-sizes
Labels: enhancement
